# Site
name: kuatroestrellas
description: Informatica Electronica Arduino Python 
meta_description: "Blog de kuatroestrellas"
logo: 'assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
paginate: 12
baseurl: 
email: 'kuatroestrellas@gmail.com'
google_analytics: ''
disqus: 'kuatroestrellas'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5c62074b338ffe0011030d64&product=sticky-share-buttons" async="async"></script>'

# Authors
authors:
  kuatroestrellas:
    name: Arturo Vargas
    display_name: Arturo
    gravatar: d6abe18424bc22ef3b78aa2b2d97c04a
    email: kuatroestrellas@gmail.com
    web: https://kuatroestrellas.github.io
    twitter: https://twitter.com/kuatroestrellas
    description: "TICs Enginer"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge